### ISSUE TITLE
babel-preset-react

### ISSUE THREAD

**Issue by lafriakh** [cretueusebiu/laravel-elixir-system#1]
i want to add babel-preset-react to compile jsx syntax.

**Comment by cretueusebiu** [comment]
Try 

```
elixir.config.js.babel.options.plugins = [
    'external-helpers', 
    'transform-object-assign', 
    'transform-es2015-modules-systemjs',
    'babel-plugin-transform-react-jsx'
];
```

Make sure you have installed `babel-plugin-transform-react-jsx`.

**Comment by Lafriakh** [comment]
it's return `ReferenceError: React is not defined`

**Comment by lafriakh** [comment]
Thank you :heart:

**Comment by cretueusebiu** [comment]
Added the plugin by default https://github.com/cretueusebiu/laravel-elixir-system/blob/master/CHANGELOG.md#v020-2016-06-17
